

# This file was *autogenerated* from the file linux_share/test_13/DT-convert.sage
from sage.all_cmdline import *   # import sage library

_sage_const_95 = Integer(95); _sage_const_2 = Integer(2); _sage_const_96 = Integer(96); _sage_const_64 = Integer(64); _sage_const_1 = Integer(1)#docker pull computop/sage

#docker run -it --mount type=bind,source="G:\My Drive\Summer Research 2020\Data\Master",target=/home/sage/linux_share computop/sage

#sage

f = open("linux_share/test_13/DTList.txt", "r")
DTList = f.readlines()
f.close()

def DTconvert(dt):
     new_dt = ""
     for x in dt:
         if x == "\n":
             y = ""
         elif ord(x) > _sage_const_95 :
             y = _sage_const_2  * (ord(x) - _sage_const_96 )
             y1 = str(y) + ","
             new_dt += str(y1)
         else:
             y = -_sage_const_2  * (ord(x) - _sage_const_64 )
             y1 = str(y) + ","
             new_dt += str(y1)
     if new_dt[len(new_dt)-_sage_const_1 ] == ",":
             new_dt = new_dt[:-_sage_const_1 ]
     return new_dt

numDTList = []

for dt in DTList:
    numDTList.append(DTconvert(dt))

with open('/home/sage/linux_share/test_13/numDTList.txt','w') as outfile: 
    outfile.write('\n'.join(numDTList))  

